
// GETTERS
export const AUTH_GET_IS_LOGEDIN = 'auth/AUTH_GET_IS_LOGEDIN';
export const AUTH_GET_ACCESS_TOKEN = 'auth/AUTH_GET_ACCESS_TOKEN';
export const AUTH_GET_REFRESH_TOKEN = 'auth/AUTH_GET_REFRESH_TOKEN';
export const AUTH_GET_USER_FULLNAME = 'auth/AUTH_GET_USER_FULLNAME';
export const AUTH_GET_USER = 'auth/AUTH_GET_USER';

export const APP_GET_IS_SIDEBAR_OPEN = 'app/APP_GET_IS_SIDEBAR_OPEN';
export const APP_GET_INITIAL_PATH = 'app/APP_GET_INITIAL_PATH';

// MUTATIONS
export const AUTH_SET_ACCESS_TOKEN = 'auth/AUTH_SET_ACCESS_TOKEN';
export const AUTH_SET_REFRESH_TOKEN = 'auth/AUTH_SET_REFRESH_TOKEN';
export const AUTH_SET_IS_LOGEDIN = 'auth/AUTH_SET_IS_LOGEDIN';
export const AUTH_SET_USER = 'auth/AUTH_SET_USER';

export const APP_SET_INITIAL_PATH = 'app/APP_SET_INITIAL_PATH';
export const APP_SET_IS_SIDEBAR_OPEN = 'app/APP_SET_IS_SIDEBAR_OPEN';

// ACTIONS
export const AUTH_ACT_LOGIN = 'auth/AUTH_ACT_LOGIN';
export const AUTH_ACT_LOGOUT = 'auth/AUTH_ACT_LOGOUT';
export const AUTH_ACT_STORE_AUTHDATA = 'auth/AUTH_ACT_STORE_AUTHDATA';
export const AUTH_ACT_WHOAMI = 'AUTH_ACT_WHOAMI';
export const AUTH_ACT_INITIALIZE = 'AUTH_ACT_INITIALIZE';
